# -*- coding: utf-8 -*-
"""MS_ML_SL2-Wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cxe0-RcHP0jCJWP0W3mpoGGD7uw5Q7p3
"""

# ===== Standard Library =====
import os
import sys
import time

# ===== Core Data =====
import numpy as np
import pandas as pd

# ===== Visualization =====
import matplotlib.pyplot as plt
import seaborn as sns

# ===== Sklearn: Model Selection =====
from sklearn.model_selection import (
    train_test_split,
    cross_validate,
    learning_curve,
    StratifiedKFold,
    GridSearchCV,
)

# ===== Sklearn: Preprocessing =====
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# ===== Sklearn: Models =====
from sklearn.dummy import DummyClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

# ===== Sklearn: Metrics =====
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)


import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

df = pd.read_csv("/content/wine.csv")

df.head()

num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

df.shape

df.isnull().sum()

plt.figure(figsize=(10,8))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix (Identify Redundancy)")
plt.show()

for col in df.columns:
    zero_count = (df[col] == 0).sum()
    print(f"Column '{col}': {zero_count} zeros")

df.shape

df.corr()['quality'].sort_values(ascending=False)

df.drop_duplicates(inplace=True)
X_wine = df.drop(['quality', 'class'], axis=1)
y_wine = df['quality']

df.dtypes

y_wine.value_counts()

plt.figure(figsize=(8, 5))
sns.countplot(x=y_wine)
plt.title("Wine Quality Class Imbalance")
plt.show()

# Stratified Split
X_train, X_test, y_train, y_test = train_test_split(
    X_wine, y_wine, test_size=0.2, stratify=y_wine, random_state=42
)

# --- 2. GENERATE ALPHAS ---
# Get candidate alphas from an unpruned tree
dt_base = DecisionTreeClassifier(random_state=42)
dt_base.fit(X_train, y_train)
path = dt_base.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas = path.ccp_alphas

# Downsample if too many alphas (for speed)
if len(ccp_alphas) > 50:
    ccp_alphas = ccp_alphas[::int(len(ccp_alphas)/50)]

print(f"Testing {len(ccp_alphas)} alphas...")

# --- 3. CROSS-VALIDATION LOOP (All Metrics) ---
scoring = {'acc': 'accuracy', 'f1_macro': 'f1_macro'}
results = {
    'alpha': [],
    'train_acc': [], 'cv_acc': [],
    'train_f1': [],  'cv_f1': []
}

for alpha in ccp_alphas:
    # Pipeline ensures scaling happens within CV folds
    pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('dt', DecisionTreeClassifier(random_state=42, ccp_alpha=alpha))
    ])

    # Run CV with return_train_score=True
    cv_scores = cross_validate(
        pipe, X_train, y_train,
        cv=5, scoring=scoring,
        return_train_score=True, n_jobs=-1
    )

    results['alpha'].append(alpha)
    results['train_acc'].append(cv_scores['train_acc'].mean())
    results['cv_acc'].append(cv_scores['test_acc'].mean())
    results['train_f1'].append(cv_scores['train_f1_macro'].mean())
    results['cv_f1'].append(cv_scores['test_f1_macro'].mean())

# --- 4. PLOT COMPLEXITY CURVE (4 Lines) ---
plt.figure(figsize=(12, 7))

# Plot Accuracy (Blue)
plt.plot(results['alpha'], results['train_acc'], label='Train Accuracy', color='blue', linestyle=':', alpha=0.6)
plt.plot(results['alpha'], results['cv_acc'], label='CV Accuracy', color='blue', marker='o')

# Plot Macro F1 (Orange)
plt.plot(results['alpha'], results['train_f1'], label='Train Macro F1', color='orange', linestyle=':', alpha=0.6)
plt.plot(results['alpha'], results['cv_f1'], label='CV Macro F1', color='orange', marker='s')

plt.xlabel("effective alpha (Regularization Strength)")
plt.ylabel("Score")
plt.title("Decision Tree Complexity: Overfitting & Imbalance (Wine)")
plt.legend()
plt.grid(True)
plt.show()

# --- 5. REPORT BEST MODEL ---
# Best based on CV Macro F1 (Syllabus Requirement)
best_idx = np.argmax(results['cv_f1'])
print(f"Best Alpha: {results['alpha'][best_idx]:.6f}")
print(f"Best CV Macro F1: {results['cv_f1'][best_idx]:.4f}")
print(f"Best CV Accuracy: {results['cv_acc'][best_idx]:.4f}")
