# -*- coding: utf-8 -*-
"""MS_ML_SL1-adult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-TSdVj2caoj3QoM-cop18I0WJeapbuM
"""

# ---- stdlib ----
import os
import sys
import time

# ---- core ----
import numpy as np
import pandas as pd

# ---- visualization ----
import matplotlib.pyplot as plt
import seaborn as sns

# ---- sklearn: preprocessing & pipelines ----
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

# ---- sklearn: model selection ----
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_validate,
    cross_val_score,
    validation_curve,
    learning_curve,
    GridSearchCV
)

# ---- sklearn: metrics ----
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    average_precision_score,
    precision_recall_curve,
    auc,
    make_scorer
)

# ---- sklearn: models ----
from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
# ---- pytorch (only if you really use it) ----
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# ---- colab only (remove if not in colab) ----
# from google.colab import files


#####################################################################################################################

"""
EDA
"""
print("............. start EDA  .........")
df = pd.read_csv("/content/adult.csv")

df.head()

df.shape



df.isnull().sum()

plt.figure(figsize=(10,8))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix (Identify Redundancy)")
plt.show()

df.nunique()

for col in df.columns:
    zero_count = (df[col] == 0).sum()
    print(f"Column '{col}': {zero_count} zeros")



df.columns

print("Unique values for 'capital-gain':")
print(df['capital-gain'].unique())
print("\nUnique values for 'capital-loss':")
print(df['capital-loss'].unique())

# 1. Education vs Income (Expect strong positive correlation)
plt.figure(figsize=(8, 5))
sns.boxplot(x='class', y='education-num', data=df)
plt.title("Education Years vs Income")
plt.show()

plt.figure(figsize=(8, 5))
sns.violinplot(x='class', y='hours-per-week', data=df)
plt.title("Work Hours vs Income Distribution")
plt.show()

# 1. Separate Features and Target
X = df.drop('class', axis=1)  # Drop the target from features
y_raw = df['class']

# 2. Encode Target to 0/1
y = y_raw.apply(lambda x: 1 if '>50K' in str(x) else 0)

print(f"Class Balance:\n{y.value_counts()}")

# Combine X_encoded (features with target-encoded categoricals) and y (numeric target)
# X_encoded contains all features, with categorical ones already target-encoded.
X_y_combined = pd.concat([X, y], axis=1)

# Calculate correlations
numeric_df = X_y_combined.select_dtypes(include=['number'])
correlations = numeric_df.corr()['class'].sort_values(ascending=False)

print("Feature Correlations with Target ('class'):")
print(correlations)

df.head()


# 1. Prepare the DataFrame for Correlation
corr_df = df.copy()

# 2. Drop Irrelevant and Redundant columns
cols_to_drop = ['fnlwgt', 'education']
corr_df = corr_df.drop(columns=[c for c in cols_to_drop if c in corr_df.columns])

# 3. Handle Categoricals for Correlation
# Simple Label Encoding allows string columns to appear in the heatmap
from sklearn.preprocessing import LabelEncoder
for col in corr_df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    corr_df[col] = le.fit_transform(corr_df[col])

# 4. Calculate and Plot
plt.figure(figsize=(12, 10))
# correlation with the target (sorted)
target_corr = corr_df.corr()['class'].sort_values(ascending=False)
print("Top Correlations:\n", target_corr)

# Full Heatmap
sns.heatmap(corr_df.corr(), annot=False, cmap='coolwarm', vmin=-1, vmax=1)
plt.title("Feature Correlation Matrix (Adult Dataset)")
plt.show()

X= X.drop(columns=['fnlwgt', 'education'])

y.head()


#####################################################################################################################

# 1. Split FIRST (Crucial for reproducibility and leakage control)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# --- 2. DEFINE PREPROCESSING PIPELINE ---
# Identify feature types
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns

# Pipeline components
# - Numerical: Impute missing (if any) -> Scale (Required for SVM/kNN/NN)
# - Categorical: Impute missing -> OneHotEncode (handle_unknown='ignore' is crucial for robustness)
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, numerical_cols),
        ('cat', cat_transformer, categorical_cols)
    ])

print("............. Finish EDA  .........")
#####################################################################################################################

print("............. Decision Tree  .........")

"""
Decision Tree
"""

# --- 1. SETUP ---
# We use the pipeline from previous Phase  (preprocessor)
# find the range of alphas that actually change the tree structure
dt_temp = DecisionTreeClassifier(random_state=42)
dt_temp.fit(preprocessor.fit_transform(X_train, y_train), y_train)

# Get valid alphas for pruning path
path = dt_temp.cost_complexity_pruning_path(preprocessor.transform(X_train), y_train)
ccp_alphas = path.ccp_alphas
# Filter: take every 20th alpha to speed up (Adult dataset has thousands)
if len(ccp_alphas) > 50:
    ccp_alphas = ccp_alphas[::int(len(ccp_alphas)/50)]

print(f"Tuning over {len(ccp_alphas)} alpha values...")

# --- 2. RUN CROSS-VALIDATION ---
train_scores = []
val_scores = []

for alpha in ccp_alphas:
    # Re-build pipeline for each alpha to prevent leakage
    clf = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', DecisionTreeClassifier(random_state=42, ccp_alpha=alpha))
    ])

    # Get CV scores (F1 is the target metric for imbalance)
    cv_score = cross_val_score(clf, X_train, y_train, cv=5, scoring='f1', n_jobs=-1)
    val_scores.append(np.mean(cv_score))

    # Get training score to show overfitting gap (Bias-Variance analysis)
    clf.fit(X_train, y_train)
    train_scores.append(f1_score(y_train, clf.predict(X_train)))

# --- 3. PLOT PRUNING CURVE
print(X_train.shape)
plt.figure(figsize=(10, 6))
plt.plot(ccp_alphas, train_scores, marker='o', label="Train F1", drawstyle="steps-post")
plt.plot(ccp_alphas, val_scores, marker='o', label="CV Validation F1", drawstyle="steps-post")
plt.xlabel("effective alpha (Regularization)")
plt.ylabel("F1 Score")
plt.title("Decision Tree Pruning Curve (Adult)")
plt.legend()
plt.grid()
plt.show()

# --- 4. SELECT BEST MODEL ---
# Find alpha with highest CV F1
best_idx = np.argmax(val_scores)
best_alpha = ccp_alphas[best_idx]
print(f"Best ccp_alpha: {best_alpha:.5f} with CV F1: {val_scores[best_idx]:.4f}")

#--- 5. Train Final (best) Tree
final_tree = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42, ccp_alpha=best_alpha))
])
final_tree.fit(X_train, y_train)

# --- 6. Report Complexity
tree_model = final_tree.named_steps['classifier']
print(f"Final Tree Depth: {tree_model.get_depth()}")
print(f"Final Leaf Count: {tree_model.get_n_leaves()}")

# --- 7. PLOT LEARNING CURVE
def plot_learning_curve(estimator, title, X, y, ylim=None, cv=5, n_jobs=-1):
    plt.figure(figsize=(10, 6))
    plt.title(title)
    if ylim is not None:
        plt.ylim(*ylim)
    plt.xlabel("Training examples")
    plt.ylabel("F1 Score")

    # Generate learning curve data
    train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=n_jobs, scoring='f1',
        train_sizes=np.linspace(0.1, 1.0, 10), random_state=42
    )

    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)

    plt.grid()

    # Plot ranges
    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1, color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")

    plt.plot(train_sizes, train_scores_mean, 'o-', color="r", label="Training score")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g", label="Cross-validation score")

    plt.legend(loc="best")
    plt.show()

# Run it on your BEST pruned model
plot_learning_curve(final_tree, "Learning Curve (Pruned Decision Tree)", X_train, y_train)

# --- 8. FINAL EVALUATION ON TEST SET ---
print("--- Final Evaluation (Held-out Test Set) ---")

# Measure Prediction Time
start_pred = time.time()
y_pred = final_tree.predict(X_test)
end_pred = time.time()
pred_time = end_pred - start_pred

# Calculate Probabilities for PR-AUC
y_proba = final_tree.predict_proba(X_test)[:, 1]
pr_auc = average_precision_score(y_test, y_proba)

print(f"Prediction Time (Test Set): {pred_time:.4f}s")
print(f"Final Test PR-AUC: {pr_auc:.4f}")
print(classification_report(y_test, y_pred))

# --- 7. CONFUSION MATRIX (Required) ---
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['<=50K', '>50K'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix: Pruned Decision Tree")
plt.show()

print("............. Decision Tree is done .........")
#####################################################################################################################
print("............. KNN  .........")

"""
KNN
"""

# --- 1. DEFINE HYPERPARAMETERS ---
# We test a range of k values (Odd numbers to avoid ties)
# Small k (High Variance), Large k (High Bias)
k_values = range(1, 20)

print(f"Tuning kNN with k={list(k_values)}...")
print("Note: This may take a few minutes. kNN prediction is expensive.")

cv_scores_mean = []
cv_scores_std = []
runtimes = []

# --- 2. GRID SEARCH WITH CROSS-VALIDATION ---
for k in k_values:
    start_time = time.time()

    # Re-build pipeline for each k
    knn_pipe = Pipeline(steps=[
        ('preprocessor', preprocessor), # Scaling happens here!
        ('classifier', KNeighborsClassifier(n_neighbors=k, n_jobs=-1))
    ])

    # Run CV
    # We focus on F1 score as the primary metric
    cv_results = cross_validate(knn_pipe, X_train, y_train, cv=5, scoring='f1', n_jobs=-1)

    # Store metrics
    cv_scores_mean.append(cv_results['test_score'].mean())
    cv_scores_std.append(cv_results['test_score'].std())
    runtimes.append(time.time() - start_time)

    print(f"k={k}: F1={cv_results['test_score'].mean():.4f} (Time: {runtimes[-1]:.1f}s)")

# --- 3. PLOT MODEL COMPLEXITY CURVE ---
plt.figure(figsize=(10, 6))
plt.errorbar(k_values, cv_scores_mean, yerr=cv_scores_std, fmt='-o', capsize=5)
plt.title("kNN Model Complexity: F1 Score vs. k (Adult Dataset)")
plt.xlabel("k (Number of Neighbors)")
plt.ylabel("Cross-Validated F1 Score")
plt.grid(True)
plt.show()

# --- 4. BEST k SELECTION ---
best_k_idx = np.argmax(cv_scores_mean)
best_k = k_values[best_k_idx]
print(f"\nBest k: {best_k} with CV F1: {cv_scores_mean[best_k_idx]:.4f}")

# --- 5.Train Final kNN Model (for runtime/comparison tables)
final_knn_pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(n_neighbors=best_k, n_jobs=-1))
])
final_knn_pipe.fit(X_train, y_train)

X_out = preprocessor.fit_transform(X_train, y_train)
X_out.shape

# --- 6. Generate Learning Curve
train_sizes, train_scores, test_scores = learning_curve(
    final_knn_pipe, X_train, y_train, cv=3, scoring='f1',
    n_jobs=-1, train_sizes=np.linspace(0.1, 1.0, 5)
)

plt.figure(figsize=(10, 6))
plt.plot(train_sizes, np.mean(train_scores, axis=1), 'o-', color="r", label="Training score")
plt.plot(train_sizes, np.mean(test_scores, axis=1), 'o-', color="g", label="Cross-validation score")
plt.title(f"Learning Curve: kNN (k={best_k})")
plt.xlabel("Training examples")
plt.ylabel("F1 Score")
plt.legend()
plt.grid()
plt.show()

#--- 7. Train on full X_train and predict on X_test
start_time = time.time()
final_knn_pipe.fit(X_train, y_train)
fit_time = time.time() - start_time

start_pred = time.time()
y_pred = final_knn_pipe.predict(X_test)
pred_time = time.time() - start_pred

print(f"kNN Training Time: {fit_time:.4f}s")
print(f"kNN Prediction Time: {pred_time:.4f}s")
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['<=50K', '>50K'])
disp.plot(cmap='Blues')
plt.title(f"Confusion Matrix: kNN (k={best_k})")
plt.show()

print("............. KNN is done  .........")

#####################################################################################################################
print("............. SVM  .........")
"""
SVM
"""

# --- 1. SETUP SUBSAMPLE FOR TUNING ---
# SVM is too slow to tune on 32k rows in Colab without waiting hours.
# We use a stratified subset of 5000 samples for the Grid Search.
print("Subsampling training data for SVM Grid Search (Speed Optimization)...")
X_tune, _, y_tune, _ = train_test_split(
    X_train, y_train, train_size=5000, stratify=y_train, random_state=42
)

# --- 2. DEFINE PIPELINE & GRID ---
svm_pipe = Pipeline([
    ('preprocessor', preprocessor), # Scaling is MANDATORY for SVM
    ('classifier', SVC(random_state=42))
])

# Test 2 Kernels: Linear (Baseline) vs RBF (Complex)
# C: Regularization (Small = Simple/Bias, Large = Complex/Variance)
# gamma: Influence of single point (RBF only)
param_grid = [
    # Linear Kernel (only C matters)
    {'classifier__kernel': ['linear'], 'classifier__C': [0.1, 1, 10]},
    # RBF Kernel (C and gamma matter)
    {'classifier__kernel': ['rbf'], 'classifier__C': [1, 2], 'classifier__gamma': ['scale', 0.1]}
]

# --- 3. RUN GRID SEARCH ---
print("Starting SVM Grid Search... (This might still take 5-10 mins)")
search = GridSearchCV(
    svm_pipe,
    param_grid,
    cv=3,           # Lower folds to speed up tuning
    scoring='f1',
    n_jobs=-1,
    verbose=1
)
search.fit(X_tune, y_tune)

# --- 4. REPORT & TRAIN FINAL MODEL ---
print(f"\nBest Params: {search.best_params_}")
print(f"Best Tuning F1: {search.best_score_:.4f}")

# Train the "Best" model on the FULL training set
print("\nTraining Final Best SVM on FULL X_train (This takes time)...")
best_svm = search.best_estimator_
start_time = time.time()
best_svm.fit(X_train, y_train) # Full training
print(f"Final Training Done. Time: {time.time() - start_time:.1f}s")

# Report Complexity (Support Vectors) - Required for Analysis
final_model = best_svm.named_steps['classifier']
print(f"Total Support Vectors: {final_model.support_vectors_.shape}")

# --- 5. PLOT COMPLEXITY CURVE (Gamma) ---
# We use the tuning subset (X_tune) to keep this fast.

param_range = np.logspace(-3, 0, 6) # Test gamma from 0.001 to 1.0
train_scores, test_scores = validation_curve(
    best_svm, X_tune, y_tune,
    param_name="classifier__gamma",
    param_range=param_range,
    cv=3, scoring="f1", n_jobs=-1
)

train_mean = np.mean(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)

plt.figure(figsize=(10, 6))
plt.semilogx(param_range, train_mean, label="Training score", color="r", marker='o')
plt.semilogx(param_range, test_mean, label="CV score", color="g", marker='o')
plt.title("SVM Complexity Curve (RBF Kernel): Effect of Gamma")
plt.xlabel("Gamma (RBF Coefficient)")
plt.ylabel("F1 Score")
plt.legend(loc="best")
plt.grid()
plt.show()



# --- 6. PLOT LEARNING CURVE ---
# We use the best found model.

train_sizes, train_scores, test_scores = learning_curve(
    best_svm, X_train, y_train,
    cv=3, scoring='f1', n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 5), # 5 points from 10% to 100% data
    random_state=42
)

train_mean = np.mean(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)

plt.figure(figsize=(10, 6))
plt.plot(train_sizes, train_mean, 'o-', color="r", label="Training score")
plt.plot(train_sizes, test_mean, 'o-', color="g", label="Cross-validation score")
plt.title("Learning Curve: SVM (RBF)")
plt.xlabel("Training examples")
plt.ylabel("F1 Score")
plt.legend(loc="best")
plt.grid()
plt.show()

#--- 7. Predict on the Test Set
# best_svm is the Pipeline from your GridSearch
y_pred_svm = best_svm.predict(X_test)

# 2. Print Classification Report (Precision/Recall/F1)
print("\n--- SVM Classification Report ---")
print(classification_report(y_test, y_pred_svm, target_names=['<=50K', '>50K']))

# 3. Generate and Plot Confusion Matrix
cm = confusion_matrix(y_test, y_pred_svm)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['<=50K', '>50K'])

# Plotting
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax)
plt.title("Confusion Matrix: SVM (RBF Kernel)")
plt.show()

print("............. SVM is done  .........")
#####################################################################################################################

print("............. MLP  .........")

"""
MLP Sklearn
"""


# --- 1. Define the SGD-Only MLP ---
# solver='sgd', momentum=0, learning_rate_init=0.01
mlp_sklearn = MLPClassifier(
    hidden_layer_sizes=(64, 32), # 2 hidden layers
    activation='relu',
    solver='sgd',          # Mandatory
    momentum=0.0,          # Mandatory: No momentum
    learning_rate='constant',
    learning_rate_init=0.1, # SGD needs higher LR than Adam
    max_iter=100,          # Epochs
    batch_size=64,
    random_state=42,
    early_stopping=True,   # Helps prevent overfitting
    n_iter_no_change=10
)

print("Training Scikit-Learn MLP (SGD)...")
# Use the full training set (scaled)
X_train_trans = preprocessor.fit_transform(X_train, y_train)
X_test_trans = preprocessor.transform(X_test) # Just for dimensionality check, don't peek!

mlp_sklearn.fit(X_train_trans, y_train)

# --- 2. Plot Loss Curve ---
plt.figure(figsize=(8, 5))
plt.plot(mlp_sklearn.loss_curve_, label='Training Loss')
# Note: Sklearn doesn't store validation loss history easily without partial_fit
# We rely on internal early stopping for validation checks
plt.title("Sklearn MLP Training Loss (SGD, No Momentum)")
plt.xlabel("Iterations (Batches)")
plt.ylabel("Log Loss")
plt.grid()
plt.legend()
plt.show()

print(f"Final Training Accuracy: {mlp_sklearn.score(X_train_trans, y_train):.4f}")
print(f"Iterations ran: {mlp_sklearn.n_iter_}")

#####################################################################################################################

"""
MLP Pytorch
"""

# --- 1. Setup Data for PyTorch ---
# Convert sparse/numpy matrices to Tensors
X_train_trans = preprocessor.fit_transform(X_train, y_train)
X_train_tensor = torch.FloatTensor(X_train_trans) # Use the preprocessed numerical array
y_train_tensor = torch.LongTensor(y_train.values)

# Create DataLoader for batching
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

# --- 2. Define Model Architecture ---
# Must match Sklearn capacity roughly (64 -> 32)
class BinaryMLP(nn.Module):
    def __init__(self, input_dim):
        super(BinaryMLP, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 2) # Output layer (2 classes)
        )

    def forward(self, x):
        return self.layers(x)

# --- 3. Training Loop (SGD Only) ---
model = BinaryMLP(input_dim=X_train_trans.shape[1]) # Correct input dimension
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.0)
criterion = nn.CrossEntropyLoss()

loss_history = []
epochs = 50

print(f"\nTraining PyTorch MLP (SGD) for {epochs} epochs...")

for epoch in range(epochs):
    epoch_loss = 0
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    # Store average loss per epoch
    loss_history.append(epoch_loss / len(train_loader))

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss_history[-1]:.4f}")

# --- 4. Plot PyTorch Curve ---
plt.figure(figsize=(8, 5))
plt.plot(loss_history, label='Training Loss', color='orange')
plt.title("PyTorch MLP Training Loss (SGD, No Momentum)")
plt.xlabel("Epochs")
plt.ylabel("Cross Entropy Loss")
plt.grid()
plt.legend()
plt.show()

#####################################################################################################################

"""
MLP Pytorch Deep vs Wide
"""

# --- 1. SETUP DATA AS TENSORS ---
# Ensure input dimension matches your One-Hot Encoded data (~100 features)
input_dim = X_train_trans.shape[1]

# Convert data
train_tensor_x = torch.FloatTensor(X_train_trans)
train_tensor_y = torch.LongTensor(y_train.values)
test_tensor_x = torch.FloatTensor(X_test_trans) # Used for validation curve
test_tensor_y = torch.LongTensor(y_test.values)

# Batches
train_loader = DataLoader(TensorDataset(train_tensor_x, train_tensor_y), batch_size=64, shuffle=True)

# --- 2. DEFINE ARCHITECTURES (Must match Sklearn) ---
class WideNet(nn.Module):
    def __init__(self, input_d):
        super(WideNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_d, 85),  # Matches Sklearn "Wide"
            nn.ReLU(),
            nn.Linear(85, 2)         # Output layer
        )
    def forward(self, x): return self.net(x)

class DeepNet(nn.Module):
    def __init__(self, input_d):
        super(DeepNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_d, 45),  # Matches Sklearn "Deep"
            nn.ReLU(),
            nn.Linear(45, 45),
            nn.ReLU(),
            nn.Linear(45, 45),
            nn.ReLU(),
            nn.Linear(45, 2)
        )
    def forward(self, x): return self.net(x)
#This function records both Training Loss and Validation Accuracy per epoch.
# --- 3. TRAINING FUNCTION (Strict SGD) ---
def train_model(model, name, epochs=50, learning_rate=0.01):
    # Requirement: SGD, No Momentum [4]
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.0)
    criterion = nn.CrossEntropyLoss()

    train_losses = []
    val_accuracies = []

    print(f"Training {name} with SGD (lr={learning_rate})...")

    for epoch in range(epochs):
        model.train()
        batch_loss = 0
        for bx, by in train_loader:
            optimizer.zero_grad()
            outputs = model(bx)
            loss = criterion(outputs, by)
            loss.backward()
            optimizer.step()
            batch_loss += loss.item()

        # Record average loss
        train_losses.append(batch_loss / len(train_loader))

        # Validation Check (Fast forward pass)
        model.eval()
        with torch.no_grad():
            val_out = model(test_tensor_x)
            _, predicted = torch.max(val_out, 1)
            acc = (predicted == test_tensor_y).sum().item() / len(test_tensor_y)
            val_accuracies.append(acc)

    return train_losses, val_accuracies

# Train both models
pt_wide = WideNet(input_dim)
pt_deep = DeepNet(input_dim)

wide_loss, wide_val = train_model(pt_wide, "PyTorch Wide")
deep_loss, deep_val = train_model(pt_deep, "PyTorch Deep")

# --- 4. PLOT COMPARISON ---
plt.figure(figsize=(12, 5))

# Subplot 1: Loss Curves
plt.subplot(1, 2, 1)

# Plot PyTorch (Use the LIST variables returned by train_model, not the model object)
if 'wide_loss' in locals():
    plt.plot(wide_loss, label='PyTorch Wide (SGD)', color='blue', linestyle='--')
if 'deep_loss' in locals():
    plt.plot(deep_loss, label='PyTorch Deep (SGD)', color='blue')

# Plot Scikit-Learn (Only if mlp_wide exists from previous steps)
if 'mlp_wide' in locals() and hasattr(mlp_wide, 'loss_curve_'):
    plt.plot(mlp_wide.loss_curve_, label='Sklearn Wide (SGD)', color='orange', linestyle='--', alpha=0.6)
if 'mlp_deep' in locals() and hasattr(mlp_deep, 'loss_curve_'):
    plt.plot(mlp_deep.loss_curve_, label='Sklearn Deep (SGD)', color='orange', alpha=0.6)

plt.title("SGD Convergence: PyTorch vs Sklearn")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.grid()

# Subplot 2: Validation Accuracy (PyTorch Only)
plt.subplot(1, 2, 2)
if 'wide_val' in locals():
    plt.plot(wide_val, label='PT Wide Val Acc', color='green', linestyle='--')
if 'deep_val' in locals():
    plt.plot(deep_val, label='PT Deep Val Acc', color='green')

plt.title("PyTorch Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.grid()

plt.tight_layout()
plt.show()

X_train_trans.shape

print("............. MLP is done  .........")
#####################################################################################################################
"""
final models comparison
"""
print("............. final models comparison  .........")
# --- 1. SETUP MODEL LIST ---
models = {
    "Decision Tree (Pruned)": final_tree,
    "k-NN (Tuned k)": final_knn_pipe,
    "SVM (RBF)": best_svm,
    "MLP (Sklearn)": mlp_sklearn, # This needs transformed data!
}

results = []

print(f"{'Model':<25} | {'Acc':<8} | {'F1':<8} | {'PR-AUC':<8} | {'Infer Time (s)':<15}")
print("-" * 75)

# --- 2. LOOP & EVALUATE ---
for name, model in models.items():
    # ERROR FIX: Check if model requires pre-transformed data
    # If the model is NOT a Pipeline (like your MLP), we must transform X_test first.
    if isinstance(model, Pipeline):
        X_input = X_test
    else:
        X_input = preprocessor.transform(X_test)

    # A. Inference Time
    start_t = time.time()
    y_pred = model.predict(X_input)
    end_t = time.time()
    infer_time = end_t - start_t

    # B. Metrics
    # Handle predict_proba for models that support it
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_input)[:, 1]
    else:
        # SVM (if probability=False) uses decision_function
        y_prob = model.decision_function(X_input)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    prauc = average_precision_score(y_test, y_prob)

    # C. Store Result
    results.append({
        "Model": name,
        "Accuracy": acc,
        "F1 Score": f1,
        "PR-AUC": prauc,
        "Inference Time (s)": infer_time
    })

    print(f"{name:<25} | {acc:.4f}   | {f1:.4f}   | {prauc:.4f}   | {infer_time:.5f}")

# --- 3. CREATE DATAFRAME ---
df_results = pd.DataFrame(results)
print(df_results)

# --- DUMMY BASELINE ---
dummy = DummyClassifier(strategy="most_frequent")
dummy.fit(X_train, y_train)
y_pred_dummy = dummy.predict(X_test)
# Dummy probabilities (0 for class 1 since it always predicts class 0)
y_prob_dummy = dummy.predict_proba(X_test)[:, 1]

print(f"Dummy Accuracy: {accuracy_score(y_test, y_pred_dummy):.4f}")
print(f"Dummy F1 Score: {f1_score(y_test, y_pred_dummy):.4f}")
print(f"Dummy PR-AUC:   {average_precision_score(y_test, y_prob_dummy):.4f}")


#####################################################################################################################
"""
Bouns part -- Activations
"""
print("............. Bouns part -- Activations ...............")

# --- 1. SETUP DATA (Re-using previous tensors) ---
# Ensure X_train_tensor, y_train_tensor, X_test_trans, y_test are ready

# Create Validation Tensor for the curve
X_val_tensor = torch.FloatTensor(X_test_trans)
y_val_tensor = torch.LongTensor(y_test.values)

# --- 2. DEFINE GENERIC MODEL ---
class ActivationModel(nn.Module):
    def __init__(self, input_dim, activation_fn):
        super(ActivationModel, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, 64),
            activation_fn(),
            nn.Linear(64, 32),
            activation_fn(),
            nn.Linear(32, 2)
        )

    def forward(self, x):
        return self.layers(x)

# --- 3. EXPERIMENT LOOP ---
activations = {
    'ReLU': nn.ReLU,
    'Tanh': nn.Tanh,
    'Sigmoid': nn.Sigmoid,
    'LeakyReLU': nn.LeakyReLU
}

results = {}
epochs = 50
learning_rate = 0.1 # SGD requires high LR

plt.figure(figsize=(10, 6))

print(f"Starting Activation Study (SGD, lr={learning_rate})...")

for name, act_fn in activations.items():
    print(f"Training with {name}...")

    # Initialize
    model = ActivationModel(X_train_tensor.shape[1], act_fn)
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.0) # STRICT SGD
    criterion = nn.CrossEntropyLoss()

    loss_curve = []

    # Train
    for epoch in range(epochs):
        epoch_loss = 0
        model.train()
        for batch_X, batch_y in train_loader:
            optimizer.zero_grad()
            output = model(batch_X)
            loss = criterion(output, batch_y)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        loss_curve.append(epoch_loss / len(train_loader))

    # Store and Plot
    results[name] = loss_curve
    plt.plot(range(1, epochs+1), loss_curve, label=name)

# --- 4. FINALIZE PLOT ---
plt.xlabel('Epochs')
plt.ylabel('Training Loss (CrossEntropy)')
plt.title('Impact of Activation Functions on SGD Convergence (Adult Dataset)')
plt.legend()
plt.grid(True)
plt.show()

print("............. eveything for Dataset A is done now ...........")
