# -*- coding: utf-8 -*-
"""MS_ML_SL2-Wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cxe0-RcHP0jCJWP0W3mpoGGD7uw5Q7p3
"""

# ===== Standard Library =====
import os
import sys
import time

# ===== Core Data =====
import numpy as np
import pandas as pd

# ===== Visualization =====
import matplotlib.pyplot as plt
import seaborn as sns

# ===== Sklearn: Model Selection =====
from sklearn.model_selection import (
    train_test_split,
    cross_validate,
    learning_curve,
    StratifiedKFold,
    GridSearchCV,
)

# ===== Sklearn: Preprocessing =====
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# ===== Sklearn: Models =====
from sklearn.dummy import DummyClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

# ===== Sklearn: Metrics =====
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)


import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset



#####################################################################################################################
print("............. EDA  .........")
"""
EDA
"""

df = pd.read_csv("wine.csv")

df.head()

num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

df.shape

df.isnull().sum()

plt.figure(figsize=(10,8))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix (Identify Redundancy)")
plt.show()

for col in df.columns:
    zero_count = (df[col] == 0).sum()
    print(f"Column '{col}': {zero_count} zeros")

df.shape

df.corr()['quality'].sort_values(ascending=False)





df.drop_duplicates(inplace=True)
X_wine = df.drop(['quality', 'class'], axis=1)
y_wine = df['quality']

df.dtypes

y_wine.value_counts()

plt.figure(figsize=(8, 5))
sns.countplot(x=y_wine)
plt.title("Wine Quality Class Imbalance")
plt.show()

#####################################################################################################################
print("............. Decision Tree  .........")

"""
Decision Tree Complexity: Overfitting & Imbalance (Wine)
"""

# --- 1. Stratified Split
X_train, X_test, y_train, y_test = train_test_split(
    X_wine, y_wine, test_size=0.2, stratify=y_wine, random_state=42
)

# --- 2. GENERATE ALPHAS ---
# Get candidate alphas from an unpruned tree
dt_base = DecisionTreeClassifier(random_state=42)
dt_base.fit(X_train, y_train)
path = dt_base.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas = path.ccp_alphas

# Downsample if too many alphas (for speed)
if len(ccp_alphas) > 50:
    ccp_alphas = ccp_alphas[::int(len(ccp_alphas)/50)]

print(f"Testing {len(ccp_alphas)} alphas...")

# --- 3. CROSS-VALIDATION LOOP (All Metrics) ---
scoring = {'acc': 'accuracy', 'f1_macro': 'f1_macro'}
results = {
    'alpha': [],
    'train_acc': [], 'cv_acc': [],
    'train_f1': [],  'cv_f1': []
}

for alpha in ccp_alphas:
    # Pipeline ensures scaling happens within CV folds
    pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('dt', DecisionTreeClassifier(random_state=42, ccp_alpha=alpha))
    ])

    # Run CV with return_train_score=True
    cv_scores = cross_validate(
        pipe, X_train, y_train,
        cv=5, scoring=scoring,
        return_train_score=True, n_jobs=-1
    )

    results['alpha'].append(alpha)
    results['train_acc'].append(cv_scores['train_acc'].mean())
    results['cv_acc'].append(cv_scores['test_acc'].mean())
    results['train_f1'].append(cv_scores['train_f1_macro'].mean())
    results['cv_f1'].append(cv_scores['test_f1_macro'].mean())

# --- 4. PLOT COMPLEXITY CURVE (4 Lines) ---
plt.figure(figsize=(12, 7))

# Plot Accuracy (Blue)
plt.plot(results['alpha'], results['train_acc'], label='Train Accuracy', color='blue', linestyle=':', alpha=0.6)
plt.plot(results['alpha'], results['cv_acc'], label='CV Accuracy', color='blue', marker='o')

# Plot Macro F1 (Orange)
plt.plot(results['alpha'], results['train_f1'], label='Train Macro F1', color='orange', linestyle=':', alpha=0.6)
plt.plot(results['alpha'], results['cv_f1'], label='CV Macro F1', color='orange', marker='s')

plt.xlabel("effective alpha (Regularization Strength)")
plt.ylabel("Score")
plt.title("Decision Tree Complexity: Overfitting & Imbalance (Wine)")
plt.legend()
plt.grid(True)
plt.show()

# --- 5. REPORT BEST MODEL ---
# Best based on CV Macro F1 (Syllabus Requirement)
best_idx = np.argmax(results['cv_f1'])
print(f"Best Alpha: {results['alpha'][best_idx]:.6f}")
print(f"Best CV Macro F1: {results['cv_f1'][best_idx]:.4f}")
print(f"Best CV Accuracy: {results['cv_acc'][best_idx]:.4f}")



# 1. Setup the Best Decision Tree Model
# Use the best ccp_alpha you found in your PDF (approx 0.00068 based on Source 10)
# If you don't use ccp_alpha, the tree will overfit wildly (Training score = 1.0)
dt_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('dt', DecisionTreeClassifier(random_state=42, ccp_alpha=0.00068))
])

# 2. Compute Learning Curves
print("Generating Decision Tree Learning Curve...")
train_sizes, train_scores, test_scores = learning_curve(
    estimator=dt_pipeline,
    X=X_train,
    y=y_train,
    cv=5,
    n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 5),
    scoring='f1_macro',
    random_state=42
)

# 3. Calculate Stats
train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)
test_std = np.std(test_scores, axis=1)

# 4. Plotting
plt.figure(figsize=(10, 6))
plt.plot(train_sizes, train_mean, 'o-', color="darkorange", label="Training Score")
plt.plot(train_sizes, test_mean, 'o-', color="navy", label="Cross-Validation Score")

# Fill variance
plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, alpha=0.1, color="darkorange")
plt.fill_between(train_sizes, test_mean - test_std, test_mean + test_std, alpha=0.1, color="navy")

plt.title("Learning Curve: Decision Tree (Pruned alpha=0.00068)", fontsize=14)
plt.xlabel("Training Examples", fontsize=12)
plt.ylabel("Macro F1 Score", fontsize=12)
plt.legend(loc="best")
plt.grid(True)
plt.show()
print("............. Decision Tree is done  .........")
#####################################################################################################################
print("............. KNN  .........")
"""
KNN Model Complexity: The Impact of 'k' on Imbalance (Wine)
"""


# --- 1. TUNING LOOP ---
# We test odd k values to avoid ties
k_values = list(range(1, 30, 2))
print(f"Tuning kNN for Wine over k={k_values}...")

results = {
    'k': [],
    'cv_acc': [],
    'cv_f1': []
}

# Define metrics
scoring = {'acc': 'accuracy', 'f1_macro': 'f1_macro'}

for k in k_values:
    # Scaling is MANDATORY for kNN (Distance based)
    # weights='distance' helps with imbalance (closer points count more)
    knn_pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier(n_neighbors=k, weights='distance', n_jobs=-1))
    ])

    cv_scores = cross_validate(knn_pipe, X_train, y_train, cv=5, scoring=scoring, n_jobs=-1)

    results['k'].append(k)
    results['cv_acc'].append(cv_scores['test_acc'].mean())
    results['cv_f1'].append(cv_scores['test_f1_macro'].mean())
    print(f"k={k}: Acc={results['cv_acc'][-1]:.4f}, F1={results['cv_f1'][-1]:.4f}")

# --- 2. PLOT COMPLEXITY CURVE ---
plt.figure(figsize=(10, 6))
plt.plot(results['k'], results['cv_acc'], marker='o', linestyle='--', label='CV Accuracy (Blue)')
plt.plot(results['k'], results['cv_f1'], marker='s', linewidth=2, color='orange', label='CV Macro F1 (Orange)')

plt.title("kNN Model Complexity: The Impact of 'k' on Imbalance (Wine)")
plt.xlabel("k (Number of Neighbors)")
plt.ylabel("Score")
plt.legend()
plt.grid(True)
plt.show()

# --- 3. BEST MODEL SELECTION ---
best_idx = np.argmax(results['cv_f1']) # Maximize F1, not Accuracy
best_k = results['k'][best_idx]
print(f"\nOptimal k: {best_k}")
print(f"Best CV Macro F1: {results['cv_f1'][best_idx]:.4f}")
print(f"Best CV Accuracy: {results['cv_acc'][best_idx]:.4f}")

best_k

# 4. Setup the Best kNN Model
# Using k=9 and weights='distance' as found in your Grid Search
knn_pipeline = Pipeline([
    ('scaler', StandardScaler()), # Scaling is mandatory for kNN
    ('knn', KNeighborsClassifier(n_neighbors=9, weights='distance', n_jobs=-1))
])

# 5. Compute Learning Curves
print("Generating kNN Learning Curve...")
train_sizes, train_scores, test_scores = learning_curve(
    estimator=knn_pipeline,
    X=X_train,
    y=y_train,
    cv=5,
    n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 5), # 10% to 100% of training data
    scoring='f1_macro',
    random_state=42
)

# 6. Calculate Means and Standard Deviations
train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)
test_std = np.std(test_scores, axis=1)

# 7. Plotting
plt.figure(figsize=(10, 6))
plt.plot(train_sizes, train_mean, 'o-', color="blue", label="Training Score")
plt.plot(train_sizes, test_mean, 'o-', color="green", label="Cross-Validation Score")

# Add standard deviation fill
plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, alpha=0.1, color="blue")
plt.fill_between(train_sizes, test_mean - test_std, test_mean + test_std, alpha=0.1, color="green")

plt.title("Learning Curve: kNN (k=9, Distance Weighted)", fontsize=14)
plt.xlabel("Training Examples", fontsize=12)
plt.ylabel("Macro F1 Score", fontsize=12)
plt.legend(loc="best")
plt.grid(True)
plt.show()

print("............. KNN is done  .........")
#####################################################################################################################

print("............. SVM  .........")
"""
SVM Model Complexity: Impact of Regularization (Wine)
"""

# Define Pipeline
svm_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(random_state=42, class_weight='balanced')) # CRITICAL for imbalance
])

# Define Grid
# We check Linear (simple) vs RBF (complex)
# C: Regularization (0.1 = strong reg, 10 = weak reg/complex model)
param_grid = [
    {'svm__kernel': ['linear'], 'svm__C': [0.1, 1, 10]},
    {'svm__kernel': ['rbf'],    'svm__C': [0.1, 1, 10], 'svm__gamma': ['scale', 0.1, 1.0]}
]

# Run Search optimizing for Macro F1 (Minority class focus)
grid = GridSearchCV(
    svm_pipe, param_grid, cv=5,
    scoring='f1_macro', n_jobs=-1, verbose=1
)
grid.fit(X_train, y_train)

# --- 3. RESULTS & ANALYSIS ---
print(f"\nBest Params: {grid.best_params_}")
print(f"Best CV Macro F1: {grid.best_score_:.4f}")

# Final Evaluation on Test Set
best_svm = grid.best_estimator_
y_pred = best_svm.predict(X_test)

print("\n--- SVM Per-Class Performance ---")
print(classification_report(y_test, y_pred, zero_division=0))

# Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Greens')
plt.title(f"SVM Confusion Matrix (Balanced Weights)")
plt.ylabel('True Quality')
plt.xlabel('Predicted Quality')
plt.show()

grid.best_estimator_

# 1. Extract Results from the existing Grid Search object
results = pd.DataFrame(grid.cv_results_)

# 2. Filter & Organize Data
# We want to compare how 'C' affects performance for different Kernels/Gammas
# 'param_svm__C' contains the C values
# 'mean_test_score' contains the Macro F1 scores (since that was your scoring metric)

plt.figure(figsize=(10, 6))

# Plot RBF Kernel (with different gamma values)
rbf_data = results[results['param_svm__kernel'] == 'rbf']
sns.lineplot(
    data=rbf_data,
    x='param_svm__C',
    y='mean_test_score',
    hue='param_svm__gamma',
    marker='o',
    palette='viridis'
    # label='RBF' # Removed the conflicting label
)

# Plot Linear Kernel (Gamma doesn't apply, so it's a single line)
linear_data = results[results['param_svm__kernel'] == 'linear']
plt.plot(
    linear_data['param_svm__C'],
    linear_data['mean_test_score'],
    label='Linear Kernel',
    color='red',
    linestyle='--',
    marker='x'
)

# 3. Formatting the "Complexity Curve"
plt.xscale('log') # C varies by orders of magnitude (0.1, 1, 10), so log scale is best
plt.title('SVM Model Complexity: Impact of Regularization (C)', fontsize=14)
plt.xlabel('Regularization Parameter C (Log Scale)', fontsize=12)
plt.ylabel('CV Macro F1 Score', fontsize=12)
plt.legend(title='Kernel / Gamma', loc='best')
plt.grid(True, which="both", ls="-", alpha=0.5)

plt.show()

# Compute Learning Curves
# train_sizes: splits the data into 5 sizes from 10% to 100%
train_sizes, train_scores, test_scores = learning_curve(
    estimator=best_svm,
    X=X_train,
    y=y_train,
    cv=5,
    n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 5), # 10% to 100% of training data
    scoring='f1_macro',
    random_state=42
)

# 3. Calculate Means and Standard Deviations
train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)
test_std = np.std(test_scores, axis=1)

# 4. Plotting
plt.figure(figsize=(10, 6))
plt.plot(train_sizes, train_mean, 'o-', color="r", label="Training Score")
plt.plot(train_sizes, test_mean, 'o-', color="g", label="Cross-Validation Score")

# Add standard deviation fill
plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, alpha=0.1, color="r")
plt.fill_between(train_sizes, test_mean - test_std, test_mean + test_std, alpha=0.1, color="g")

plt.title("Learning Curve: SVM (RBF Kernel, Weighted)", fontsize=14)
plt.xlabel("Training Examples", fontsize=12)
plt.ylabel("Macro F1 Score", fontsize=12)
plt.legend(loc="best")
plt.grid(True)
plt.show()

print("............. SVM is done  .........")
#####################################################################################################################
print("............. MLP  .........")
"""
MLP Sklearn
"""


nn_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('mlp', MLPClassifier(
        hidden_layer_sizes=(130,),
        activation='relu',
        solver='sgd',
        learning_rate_init=0.1,
        momentum=0.0,
        max_iter=1000,  # Increased to ensure convergence
        random_state=42
    ))
])

# --- 2. CALCULATE LEARNING CURVE (Size vs. Score) ---
print("Generating Learning Curves (this may take a moment)...")
train_sizes, train_scores, test_scores = learning_curve(
    nn_pipeline,
    X_train, y_train,
    cv=5,
    scoring='f1_macro', # Using Macro F1 due to imbalance
    n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 5) # 10% to 100% of data
)

# Calculate means and standard deviations
train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)
test_std = np.std(test_scores, axis=1)

# --- 3. PLOT LEARNING CURVE ---
plt.figure(figsize=(14, 6))

# Subplot 1: Sample Size Learning Curve (Bias/Variance)
plt.subplot(1, 2, 1)
plt.plot(train_sizes, train_mean, 'o-', color="blue", label="Training Score")
plt.plot(train_sizes, test_mean, 'o-', color="orange", label="CV Score")
plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, alpha=0.1, color="blue")
plt.fill_between(train_sizes, test_mean - test_std, test_mean + test_std, alpha=0.1, color="orange")

plt.title("NN Learning Curve: Bias vs. Variance (Wine)")
plt.xlabel("Training Set Size")
plt.ylabel("Macro F1 Score")
plt.legend(loc="best")
plt.grid(True)

# Subplot 2: Loss Curve (Optimization Behavior)
# We must fit the model once to get the loss_curve_ attribute
plt.subplot(1, 2, 2)
nn_pipeline.fit(X_train, y_train)
loss_values = nn_pipeline.named_steps['mlp'].loss_curve_

plt.plot(loss_values, color='red', label='Training Loss')
plt.title("NN Optimization: Loss vs. Epochs (SGD)")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

#####################################################################################################################
"""
MLP Pytorch deep vs Wide
"""

# Re-scale data specifically for NN (Sensitive to scale)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Map labels 1..8 to 0..7 for PyTorch CrossEntropy
unique_labels = sorted(y_wine.unique())
label_map = {val: idx for idx, val in enumerate(unique_labels)}
y_train_map = y_train.map(label_map).values
y_test_map = y_test.map(label_map).values

# ==========================================
# 3. PYTORCH IMPLEMENTATION (Capacity Study)
# ==========================================
print(f"\n--- 2. PyTorch Capacity Scaling (Deep vs. Wide) ---")

# Convert to Tensors
X_train_t = torch.FloatTensor(X_train_scaled)
y_train_t = torch.LongTensor(y_train_map)
X_test_t = torch.FloatTensor(X_test_scaled)
y_test_t = torch.LongTensor(y_test_map)

# Create DataLoader
train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=64, shuffle=True)

# --- Define Architectures (Constrained to ~2500 parameters) ---
input_dim = X_train.shape[1]
output_dim = len(unique_labels)

# WIDE: 1 Hidden Layer (130 units)
# Params: (11*130) + 130 + (130*7) + 7 = 2477
class WideNet(nn.Module):
    def __init__(self):
        super(WideNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 130),
            nn.ReLU(),
            nn.Linear(130, output_dim)
        )
    def forward(self, x): return self.net(x)

# DEEP: 3 Hidden Layers (30 units each)
# Params: (11*30)+30 + (30*30)+30 + (30*30)+30 + (30*7)+7 = ~2400
class DeepNet(nn.Module):
    def __init__(self):
        super(DeepNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 30),
            nn.ReLU(),
            nn.Linear(30, 30),
            nn.ReLU(),
            nn.Linear(30, 30),
            nn.ReLU(),
            nn.Linear(30, output_dim)
        )
    def forward(self, x): return self.net(x)

# --- Training Function (Strict SGD) ---
def train_and_evaluate(model, name, epochs=150):
    # REQUIREMENT: SGD only, no momentum, no Adam
    optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.0)
    criterion = nn.CrossEntropyLoss()

    metrics = {'loss': [], 'val_f1': [], 'val_acc': []}

    for epoch in range(epochs):
        model.train()
        batch_loss = 0
        for bx, by in train_loader:
            optimizer.zero_grad()
            output = model(bx)
            loss = criterion(output, by)
            loss.backward()
            optimizer.step()
            batch_loss += loss.item()

        # Validation stats
        model.eval()
        with torch.no_grad():
            val_out = model(X_test_t)
            _, preds = torch.max(val_out, 1)
            f1 = f1_score(y_test_t, preds, average='macro')
            acc = accuracy_score(y_test_t, preds)

        metrics['loss'].append(batch_loss / len(train_loader))
        metrics['val_f1'].append(f1)
        metrics['val_acc'].append(acc)

    return metrics

# Run Experiments
wide_model = WideNet()
deep_model = DeepNet()

print("Training Wide Model...")
wide_hist = train_and_evaluate(wide_model, "Wide")
print(f"Final Wide Macro F1: {wide_hist['val_f1'][-1]:.4f}")

print("Training Deep Model...")
deep_hist = train_and_evaluate(deep_model, "Deep")
print(f"Final Deep Macro F1: {deep_hist['val_f1'][-1]:.4f}")

# ==========================================
# 4. PLOTTING RESULTS (Syllabus Requirement)
# ==========================================
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Training Loss (Convergence Speed)
ax1.plot(wide_hist['loss'], label='Wide (1 Layer, 130 units)', color='blue')
ax1.plot(deep_hist['loss'], label='Deep (3 Layers, 30 units)', color='red')
ax1.set_title("Training Loss: SGD Convergence (No Momentum)")
ax1.set_xlabel("Epochs")
ax1.set_ylabel("Cross Entropy Loss")
ax1.legend()
ax1.grid(True)

# Plot 2: Validation Macro F1 (Generalization)
ax2.plot(wide_hist['val_f1'], label='Wide F1', color='blue')
ax2.plot(deep_hist['val_f1'], label='Deep F1', color='red')
ax2.set_title("Validation Macro F1 (Imbalanced Classes)")
ax2.set_xlabel("Epochs")
ax2.set_ylabel("Macro F1 Score")
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()

# Final Report on best PyTorch model
print("\n--- Final PyTorch Per-Class Report (Wide Model) ---")
wide_model.eval()
with torch.no_grad():
    _, final_preds = torch.max(wide_model(X_test_t), 1)
    # Remap 0-6 back to 3-9 for display
    print(classification_report(y_test_t, final_preds, zero_division=0))

print("............. MLP is done .........")
#####################################################################################################################

"""
Final models comparison
"""
print("............. Final models comparison  .........")

# --- 1. SETUP BEST MODELS
models = {
    "Baseline (Dummy)": DummyClassifier(strategy="most_frequent"),

    # Best Params : ccp_alpha=0.00068
    "Decision Tree": Pipeline([
        ('scaler', StandardScaler()),
        ('dt', DecisionTreeClassifier(random_state=42, ccp_alpha=0.00068, class_weight='balanced'))
    ]),

    # Best Params f: k=9, distance weights
    "kNN": Pipeline([
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier(n_neighbors=9, weights='distance', n_jobs=-1))
    ]),

    # Best Params : C=2, gamma=0.1, RBF
    "SVM (RBF)": Pipeline([
        ('scaler', StandardScaler()),
        ('svm', SVC(C=2, gamma=0.1, kernel='rbf', class_weight='balanced', random_state=42))
    ]),

    "Neural Net": nn_pipeline
}

# --- 2. EXECUTION LOOP ---
results = []
conf_matrices = {}

print(f"{'Model':<20} | {'Train Time (s)':<15} | {'Predict Time (s)':<15} | {'Macro F1':<10}")
print("-" * 70)

for name, model in models.items():
    # A. Timing Training
    start_train = time.time()
    model.fit(X_train, y_train)
    end_train = time.time()
    train_time = end_train - start_train

    # B. Timing Prediction
    start_pred = time.time()
    y_pred = model.predict(X_test)
    end_pred = time.time()
    pred_time = end_pred - start_pred

    # C. Metrics
    # Convert PyTorch tensors back to numpy if necessary
    if name == "Neural Net (Wide)":
        # Handle potential tensor output from the wrapper
        if hasattr(y_pred, 'numpy'): y_pred = y_pred.numpy()

    score = f1_score(y_test, y_pred, average='macro')

    # Store results
    results.append({
        "Model": name,
        "Train Time": train_time,
        "Predict Time": pred_time,
        "Macro F1": score
    })

    conf_matrices[name] = confusion_matrix(y_test, y_pred)

    print(f"{name:<20} | {train_time:<15.4f} | {pred_time:<15.4f} | {score:<10.4f}")

# --- 3. VISUALIZATION: CONFUSION MATRICES ---
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, (name, matrix) in enumerate(conf_matrices.items()):
    sns.heatmap(matrix, annot=True, fmt='d', cmap='Greens', ax=axes[i])
    axes[i].set_title(f"{name}\nMacro F1: {results[i]['Macro F1']:.3f}")
    axes[i].set_ylabel("True Label")
    axes[i].set_xlabel("Predicted Label")

# Hide empty subplot if any
if len(models) < 6:
    axes[-1].axis('off')

plt.tight_layout()
plt.show()

# --- 4. RUNTIME TABLE FOR REPORT ---
df_results = pd.DataFrame(results)
print("\n--- Final Runtime & Performance Table ---")
print(df_results.sort_values(by="Macro F1", ascending=False))

print("............. eveything for Dataset B: Wine is done now ...........")
